---
# ====== Application: HOSPITAL MANAGEMENT SYSTEM =============
identification: 
  name: HOSPITAL MANAGEMENT SYSTEM
  alias: HOSPITAL-MANAGEMENT-SYSTEM
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: false
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 43963166572079909520

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: WKSP_DEROSPACE

globalization: 
  primary-language: English (en)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: HOSPITAL MANAGEMENT SYSTEM

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--hidden
  - t-TreeNav--styleA
  list-position: Side
  list: Navigation Menu # 43963167414923909521

navigation-bar: 
  implementation: List
  list: Navigation Bar # 43963168648194909524
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 15625587005180

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: HOSPITAL MANAGEMENT SYSTEM

component-settings: 
- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 43963161999611909515
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 15624814726403

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 43963162252116909516
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 15624814726486

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 43963162534763909517
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 15624814726500

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 43963162880741909517
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 15624814726512

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 43963163106977909518
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 15624814726568

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 43963163436600909518
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 15624814726580

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 43963163798932909518
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 15624814726589

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 43963164095054909518
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 15624814726603

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 43963164322965909519
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 15624814726621

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 43963164653975909519
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 15624814726639

- # ====== Component Setting: NATIVE_IR ========================
  id: 43963164916594909519
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 15624814726658

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 43963165271286909519
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 15624814726680

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 43963165514475909519
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 15624814726698

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 43963165878257909519
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 15624814726712

